const en = {
  rbVscodeOpen: "Open in VS Code", rbVscodeTargets: "Also reads remote.SSH.configFile from the default VS Code user settings (JSONC). Hosts from that file are marked VS Code. Custom profiles and portable settings are not scanned.", rbVscodeHint: "Connect VS Code Remote - SSH to this same host, then paste the proxy variables and CLI launch commands into its remote terminal. The bridge remains owned by ProxyEnv. Terminal exports do not reconfigure an already-running VS Code Server or extension host.", rbVscodeError: "Could not open the reviewed SSH target in VS Code. Check that VS Code and Remote - SSH are installed, and select a host from the same SSH configuration used by VS Code.",
  rbTitle: "Remote environment bridge", rbHint: "Share your current local proxy and CC Switch with a server or VM over SSH.",
  rbOpen: "Configure bridge", rbView: "View bridge", rbTarget: "Remote environment", rbCapabilities: "Bridge capabilities", rbPreview: "Review bridge", rbStatus: "Bridge status",
  rbAlias: "SSH host alias", rbEmpty: "No explicit Host aliases found in ~/.ssh/config. Add a host using OpenSSH, then refresh.",
  rbRequirements: "Uses your existing OpenSSH keys and agent. First connect in your terminal to verify the host key. Remote: a non-root Linux account with ss, flock and coreutils.",
  rbCheck: "Check connection", rbChecked: "SSH connection verified", rbRefresh: "Refresh hosts", rbNext: "Continue", rbBack: "Back", rbClose: "Close",
  rbProxy: "Current local proxy", rbNoProxy: "The active proxy is unavailable. Select an available proxy on the home page.",
  rbCc: "CC Switch local routing", rbCcHint: "Checks only the loopback port, not service identity. Confirm this is your CC Switch routing port and routing is enabled for the desired CLI.",
  rbLocalPort: "Local routing port", rbDetect: "Check local port", rbDetected: "Local port is listening", rbRemotePort: "Remote port", rbPortHint: "Use distinct ports between 1024 and 65535.",
  rbSafety: "Remote binding: 127.0.0.1 only. The tunnel lasts for this ProxyEnv session. No shell startup files are changed.",
  rbConnect: "Establish bridge", rbDisconnect: "Disconnect bridge", rbDisconnectHint: "Remote programs will lose bridge access. Saved CLI overlays remain available for restore.", rbConfirm: "Confirm", rbCancel: "Cancel",
  rbReconnect: "Configure again", rbStaleHint: "The active proxy has changed. This tunnel still uses its original endpoint. Disconnect and establish a new bridge to use the current proxy.",
  rbUnavailableHint: "A local endpoint is unavailable. Check the selected proxy or CC Switch. The bridge will not switch endpoints automatically.",
  rbLocal: "Local", rbRemote: "Remote", rbCopy: "Copy environment variables", rbCopied: "Copied", rbTest: "Test bridge", rbTestHint: "Only this action contacts gstatic.com through the remote proxy. No AI prompts are sent.", rbTested: "Remote network test passed",
  rbCodex: "Configure Codex", rbClaude: "Configure Claude Code", rbRestoreCodex: "Restore Codex overlay", rbRestoreClaude: "Restore Claude overlay",
  rbConfigHint: "Creates a dedicated overlay: Codex CLI 0.134+ (0.x), or Claude Code 2.x. Existing defaults and credentials stay in place. Use the displayed command to opt in; higher-priority settings may override it. PROXY_MANAGED is a public placeholder, not a key.",
  rbBefore: "Before", rbAfter: "After", rbAbsent: "File does not exist", rbApply: "Apply reviewed configuration", rbApplied: "Configuration verified", rbLaunch: "Remote launch command", rbCopyLaunch: "Copy launch command", rbRestoreHint: "Restore the original dedicated overlay from its remote backup. If another program changed the file, restore stops without overwriting it.", rbRestored: "Original overlay restored",
  rbBusy: "Working…", rbFailed: "The operation failed. Check your SSH target and local endpoints, then retry.",
  rbSshError: "SSH could not connect. Check the host key in your terminal, existing key/agent authentication, and SSH configuration. No server settings were changed.",
  rbForwardError: "The reverse forward could not be established. Check remote port occupancy and SSH forwarding policy. Server settings were not changed.",
  rbBindingError: "The remote listener could not be verified as loopback-only. The new tunnel was closed. Check GatewayPorts with your administrator.",
  rbConfigError: "Configuration conflict or unsupported file. No conflicting edits were overwritten. Review the dedicated overlay and recovery files on the remote host.",
  rbDependencyError: "Unsupported remote environment or missing tool. Use a non-root Linux account with ss, flock and coreutils; CLI overlays require Codex 0.134+ (0.x) or Claude Code 2.x.",
  rbPortError: "Invalid or occupied remote port. Choose distinct unused ports in 1024–65535.", rbActiveError: "The selected proxy changed or is unavailable. Return home to check it, then review the bridge again.",
  rbStates: { disconnected: "Disconnected", connecting: "Connecting", connected: "Connected", stale: "Configuration changed", unavailable: "Unavailable", error: "Connection failed" },
};
type Labels = { [K in keyof typeof en]: K extends "rbStates" ? Record<keyof typeof en.rbStates, string> : string };
const zh: Labels = {
  rbVscodeOpen:"在 VS Code 中打开", rbVscodeTargets:"同时读取 VS Code 默认用户设置（JSONC）中的 remote.SSH.configFile；该文件中的主机标注为 VS Code。不扫描自定义 Profile 或便携版设置。", rbVscodeHint:"在 VS Code Remote - SSH 中连接同一主机，再把代理变量和 CLI 启动命令粘贴到远程终端。桥接由 ProxyEnv 独立维护。终端 export 不会重新配置已运行的 VS Code Server 或扩展宿主。", rbVscodeError:"无法在 VS Code 中打开已确认的 SSH 目标。请确认已安装 VS Code 与 Remote - SSH，并选择与 VS Code 使用同一 SSH 配置的主机。",
  rbTitle:"远程环境桥接", rbHint:"通过 SSH 让服务器或虚拟机复用当前本机代理与 CC Switch。", rbOpen:"配置远程桥接", rbView:"查看桥接", rbTarget:"选择远程环境", rbCapabilities:"选择桥接能力", rbPreview:"确认桥接配置", rbStatus:"桥接状态",
  rbAlias:"SSH 主机别名", rbEmpty:"未在 ~/.ssh/config 中发现明确的 Host 别名。请先通过 OpenSSH 配置主机，再刷新。", rbRequirements:"复用现有 OpenSSH 密钥与 Agent。请先在终端连接并确认主机指纹。远端需使用非 root Linux 账户，并具备 ss、flock 和 coreutils。",
  rbCheck:"检查连接", rbChecked:"SSH 连接已验证", rbRefresh:"刷新主机", rbNext:"下一步", rbBack:"上一步", rbClose:"关闭", rbProxy:"当前本机代理", rbNoProxy:"当前活动代理不可用，请回到首页选择可用代理。",
  rbCc:"CC Switch 本地路由", rbCcHint:"仅检查 Loopback 端口监听，不判断服务身份。请确认该端口属于 CC Switch，且已为所需 CLI 开启路由。", rbLocalPort:"本地路由端口", rbDetect:"检查本地端口", rbDetected:"本地端口正在监听", rbRemotePort:"远程端口", rbPortHint:"端口范围 1024–65535，两个桥接不能使用相同端口。",
  rbSafety:"远端仅绑定 127.0.0.1。隧道仅在本次 ProxyEnv 运行期间有效，不修改 Shell 启动文件。", rbConnect:"建立桥接", rbDisconnect:"断开桥接", rbDisconnectHint:"远程程序将无法继续通过桥接访问。已保存的 CLI 接入配置仍可恢复。", rbConfirm:"确认", rbCancel:"取消", rbReconnect:"重新配置",
  rbStaleHint:"当前活动代理已变化，现有隧道仍使用原端点。请断开并重新建立桥接以使用当前代理。", rbUnavailableHint:"本地端点不可用，请检查所选代理或 CC Switch。桥接不会自动切换端点。", rbLocal:"本机", rbRemote:"远端", rbCopy:"复制环境变量", rbCopied:"已复制", rbTest:"测试桥接", rbTestHint:"仅点击此按钮才会经远程代理访问 gstatic.com，不发送 AI Prompt。", rbTested:"远程联网测试通过",
  rbCodex:"配置 Codex", rbClaude:"配置 Claude Code", rbRestoreCodex:"恢复 Codex 接入配置", rbRestoreClaude:"恢复 Claude 接入配置", rbConfigHint:"创建独立接入配置，支持 Codex CLI 0.134+（0.x）和 Claude Code 2.x。保留原有默认配置与凭据，使用下方命令主动启用；更高优先级设置可能覆盖它。PROXY_MANAGED 是公开占位符，不是密钥。",
  rbBefore:"修改前", rbAfter:"修改后", rbAbsent:"文件不存在", rbApply:"确认应用配置", rbApplied:"配置已写入并验证", rbLaunch:"远端启动命令", rbCopyLaunch:"复制启动命令", rbRestoreHint:"从远端备份恢复原始独立接入配置。如果第三方已修改文件，将停止恢复，避免覆盖。", rbRestored:"已恢复原始接入配置", rbBusy:"正在处理…", rbFailed:"操作未完成，请检查 SSH 目标和本地端点后重试。",
  rbSshError:"SSH 无法连接。请在终端检查主机指纹、密钥或 Agent 认证，以及 SSH 配置。未修改服务器设置。", rbForwardError:"无法建立反向转发，请检查远程端口占用和 SSH 转发策略。未修改服务器设置。", rbBindingError:"无法确认远端仅监听 Loopback，新隧道已关闭。请联系管理员检查 GatewayPorts 策略。", rbConfigError:"配置冲突或文件不受支持，未覆盖冲突修改。请在远端检查独立接入配置及恢复文件。", rbDependencyError:"远端环境不受支持或缺少工具。需使用具备 ss、flock、coreutils 的非 root Linux 账户；接入配置要求 Codex 0.134+（0.x）或 Claude Code 2.x。", rbPortError:"远程端口无效或已占用，请选择 1024–65535 范围内互不重复的空闲端口。", rbActiveError:"活动代理已变化或不可用，请回首页检查后重新预览桥接。",
  rbStates:{disconnected:"未连接",connecting:"正在连接",connected:"已连接",stale:"配置已变化",unavailable:"当前不可用",error:"连接失败"},
};
const ja: Labels = {
  rbVscodeOpen:"VS Code で開く", rbVscodeTargets:"VS Code の既定ユーザー設定（JSONC）の remote.SSH.configFile も読みます。該当ホストは VS Code と表示します。カスタム Profile とポータブル設定は対象外です。", rbVscodeHint:"Remote - SSH で同じホストに接続し、リモートターミナルに環境変数と CLI コマンドを貼り付けてください。ブリッジは ProxyEnv が管理します。export は起動済みの Server や拡張ホストを再設定しません。", rbVscodeError:"VS Code で接続先を開けません。VS Code と Remote - SSH のインストール、および SSH 設定ファイルの一致を確認してください。",
  rbTitle:"リモート環境ブリッジ",rbHint:"SSH 経由でサーバーや VM と現在のプロキシ・CC Switch を共有します。",rbOpen:"ブリッジを設定",rbView:"ブリッジを表示",rbTarget:"接続先を選択",rbCapabilities:"機能を選択",rbPreview:"設定を確認",rbStatus:"ブリッジの状態",rbAlias:"SSH ホスト別名",rbEmpty:"~/.ssh/config に明示的な Host がありません。OpenSSH で追加して更新してください。",rbRequirements:"既存の鍵と Agent を使用します。先にターミナルでホスト鍵を確認してください。接続先は非 root の Linux、ss・flock・coreutils が必要です。",rbCheck:"接続を確認",rbChecked:"SSH 接続を確認済み",rbRefresh:"ホストを更新",rbNext:"次へ",rbBack:"戻る",rbClose:"閉じる",rbProxy:"現在のローカルプロキシ",rbNoProxy:"プロキシが利用できません。ホームで利用可能なプロキシを選択してください。",rbCc:"CC Switch ローカルルーティング",rbCcHint:"ポートの待ち受けのみ確認します。CC Switch のポートと CLI のルーティング有効化を確認してください。",rbLocalPort:"ローカルポート",rbDetect:"ポートを確認",rbDetected:"ポートは待ち受け中です",rbRemotePort:"リモートポート",rbPortHint:"1024～65535 の異なるポートを指定してください。",rbSafety:"リモートは 127.0.0.1 のみ。ProxyEnv の実行中だけ有効です。Shell 起動ファイルは変更しません。",rbConnect:"ブリッジを接続",rbDisconnect:"ブリッジを切断",rbDisconnectHint:"リモートプログラムの接続が失われます。保存済み CLI 設定は復元できます。",rbConfirm:"確認",rbCancel:"キャンセル",rbReconnect:"再設定",rbStaleHint:"現在のプロキシが変更されました。既存の接続先は保持されています。切断してから再接続してください。",rbUnavailableHint:"ローカルの接続先を利用できません。プロキシまたは CC Switch を確認してください。自動切替は行いません。",rbLocal:"ローカル",rbRemote:"リモート",rbCopy:"環境変数をコピー",rbCopied:"コピーしました",rbTest:"ブリッジをテスト",rbTestHint:"この操作のみがリモートプロキシ経由で gstatic.com に接続します。AI リクエストは送りません。",rbTested:"ネットワークテスト成功",rbCodex:"Codex を設定",rbClaude:"Claude Code を設定",rbRestoreCodex:"Codex 設定を復元",rbRestoreClaude:"Claude 設定を復元",rbConfigHint:"専用設定を作成します。Codex CLI 0.134+（0.x）と Claude Code 2.x に対応。既存の設定と認証情報を保持します。表示されたコマンドで有効にしてください。上位設定による上書きがあり得ます。PROXY_MANAGED は公開プレースホルダーです。",rbBefore:"変更前",rbAfter:"変更後",rbAbsent:"ファイルなし",rbApply:"確認して適用",rbApplied:"設定を検証済み",rbLaunch:"リモート起動コマンド",rbCopyLaunch:"起動コマンドをコピー",rbRestoreHint:"リモートバックアップから専用設定を復元します。他の変更があれば上書きせず停止します。",rbRestored:"元の設定を復元しました",rbBusy:"処理中…",rbFailed:"操作に失敗しました。SSH とローカル接続先を確認して再試行してください。",rbSshError:"SSH 接続に失敗しました。ターミナルでホスト鍵、認証、設定を確認してください。サーバー設定は変更していません。",rbForwardError:"転送できません。ポートの使用状況と SSH 転送ポリシーを確認してください。サーバー設定は変更していません。",rbBindingError:"Loopback のみの待ち受けを確認できず、新しい接続を閉じました。管理者に GatewayPorts を確認してください。",rbConfigError:"設定が競合するか未対応です。競合を上書きしていません。リモートの専用設定と復元ファイルを確認してください。",rbDependencyError:"非対応の環境またはツール不足です。非 root Linux と ss・flock・coreutils、Codex 0.134+（0.x）または Claude Code 2.x が必要です。",rbPortError:"ポートが無効か使用中です。1024～65535 の空きポートを選択してください。",rbActiveError:"プロキシが変更されたか利用できません。ホームで確認して再設定してください。",rbStates:{disconnected:"未接続",connecting:"接続中",connected:"接続済み",stale:"設定変更あり",unavailable:"利用不可",error:"接続失敗"},
};
const ko: Labels = {
  rbVscodeOpen:"VS Code에서 열기", rbVscodeTargets:"VS Code 기본 사용자 설정(JSONC)의 remote.SSH.configFile도 읽습니다. 해당 호스트는 VS Code로 표시됩니다. 사용자 지정 Profile 및 휴대용 설정은 검색하지 않습니다.", rbVscodeHint:"Remote - SSH로 같은 호스트에 연결한 뒤 원격 터미널에 프록시 변수와 CLI 명령을 붙여 넣으세요. 브리지는 ProxyEnv가 관리합니다. 터미널 export는 실행 중인 Server나 확장 호스트를 다시 설정하지 않습니다.", rbVscodeError:"VS Code에서 대상 호스트를 열 수 없습니다. VS Code와 Remote - SSH 설치 및 SSH 설정 파일 일치 여부를 확인하세요.",
  rbTitle:"원격 환경 브리지",rbHint:"SSH로 서버 또는 VM에서 현재 프록시와 CC Switch를 사용합니다.",rbOpen:"브리지 설정",rbView:"브리지 보기",rbTarget:"원격 환경 선택",rbCapabilities:"기능 선택",rbPreview:"설정 확인",rbStatus:"브리지 상태",rbAlias:"SSH 호스트 별칭",rbEmpty:"~/.ssh/config에 명시적인 Host가 없습니다. OpenSSH로 호스트를 추가한 후 새로 고치세요.",rbRequirements:"기존 키와 Agent를 사용합니다. 터미널에서 호스트 키를 먼저 확인하세요. 원격에는 ss, flock, coreutils가 있는 비 root Linux 계정이 필요합니다.",rbCheck:"연결 확인",rbChecked:"SSH 연결 확인됨",rbRefresh:"호스트 새로 고침",rbNext:"다음",rbBack:"이전",rbClose:"닫기",rbProxy:"현재 로컬 프록시",rbNoProxy:"프록시를 사용할 수 없습니다. 홈에서 사용 가능한 프록시를 선택하세요.",rbCc:"CC Switch 로컬 라우팅",rbCcHint:"포트 수신만 확인합니다. CC Switch 포트인지, 해당 CLI의 라우팅이 켜져 있는지 확인하세요.",rbLocalPort:"로컬 라우팅 포트",rbDetect:"로컬 포트 확인",rbDetected:"포트가 수신 중입니다",rbRemotePort:"원격 포트",rbPortHint:"1024–65535 범위에서 서로 다른 포트를 사용하세요.",rbSafety:"원격은 127.0.0.1에만 바인딩합니다. ProxyEnv 실행 중에만 유효하며 Shell 시작 파일을 변경하지 않습니다.",rbConnect:"브리지 연결",rbDisconnect:"브리지 연결 해제",rbDisconnectHint:"원격 프로그램의 브리지 연결이 끊깁니다. 저장된 CLI 설정은 복원할 수 있습니다.",rbConfirm:"확인",rbCancel:"취소",rbReconnect:"다시 설정",rbStaleHint:"현재 프록시가 변경되었습니다. 기존 터널은 원래 대상을 사용합니다. 연결을 해제한 후 다시 설정하세요.",rbUnavailableHint:"로컬 대상을 사용할 수 없습니다. 프록시 또는 CC Switch를 확인하세요. 대상은 자동으로 전환되지 않습니다.",rbLocal:"로컬",rbRemote:"원격",rbCopy:"환경 변수 복사",rbCopied:"복사됨",rbTest:"브리지 테스트",rbTestHint:"이 버튼만 원격 프록시를 통해 gstatic.com에 접속합니다. AI 요청은 보내지 않습니다.",rbTested:"원격 네트워크 테스트 통과",rbCodex:"Codex 설정",rbClaude:"Claude Code 설정",rbRestoreCodex:"Codex 설정 복원",rbRestoreClaude:"Claude 설정 복원",rbConfigHint:"전용 설정을 생성합니다. Codex CLI 0.134+ (0.x) 또는 Claude Code 2.x를 지원합니다. 기존 기본 설정과 인증 정보를 유지합니다. 표시된 명령으로 사용하며 상위 설정이 덮어쓸 수 있습니다. PROXY_MANAGED는 공개 자리표시자입니다.",rbBefore:"변경 전",rbAfter:"변경 후",rbAbsent:"파일 없음",rbApply:"설정 확인 후 적용",rbApplied:"설정 검증 완료",rbLaunch:"원격 실행 명령",rbCopyLaunch:"실행 명령 복사",rbRestoreHint:"원격 백업에서 원래 전용 설정을 복원합니다. 다른 프로그램이 변경했다면 덮어쓰지 않고 중단합니다.",rbRestored:"원래 설정 복원됨",rbBusy:"처리 중…",rbFailed:"작업이 실패했습니다. SSH 대상과 로컬 포트를 확인한 후 다시 시도하세요.",rbSshError:"SSH 연결 실패. 터미널에서 호스트 키, 키/Agent 인증, SSH 설정을 확인하세요. 서버 설정은 변경하지 않았습니다.",rbForwardError:"역방향 전달 실패. 원격 포트 점유와 SSH 전달 정책을 확인하세요. 서버 설정은 변경하지 않았습니다.",rbBindingError:"Loopback 전용 수신을 확인할 수 없어 새 터널을 닫았습니다. 관리자에게 GatewayPorts 정책을 확인하세요.",rbConfigError:"설정 충돌 또는 미지원 파일입니다. 충돌한 변경을 덮어쓰지 않았습니다. 원격의 전용 설정과 복구 파일을 확인하세요.",rbDependencyError:"미지원 원격 환경 또는 도구 누락입니다. ss, flock, coreutils가 있는 비 root Linux와 Codex 0.134+ (0.x) 또는 Claude Code 2.x가 필요합니다.",rbPortError:"잘못되었거나 사용 중인 포트입니다. 1024–65535 범위의 서로 다른 빈 포트를 선택하세요.",rbActiveError:"프록시가 변경되었거나 사용할 수 없습니다. 홈에서 확인한 후 다시 미리 보세요.",rbStates:{disconnected:"연결 안 됨",connecting:"연결 중",connected:"연결됨",stale:"설정 변경됨",unavailable:"사용 불가",error:"연결 실패"},
};
export const remoteBridgeMessages = { en, "zh-CN": zh, ja, ko };
export type RemoteBridgeCopy = Labels;

export function bridgeError(code: unknown, copy: Labels): string {
  const value = typeof code === "string" ? code : "";
  if (["vscodeMissing","vscodeConfigInvalid","vscodeConfigMismatch"].includes(value)) return copy.rbVscodeError;
  if (["sshConfigChanged","sshMissing","sshConfigMissing","sshConfigUnsafe","sshTimeout","hostKey","sshAuth","sshFailed","invalidTarget"].includes(value)) return copy.rbSshError;
  if (value === "forwardDenied") return copy.rbForwardError;
  if (value === "unsafeBinding") return copy.rbBindingError;
  if (["configConflict","unsafePath","noBackup","rollbackConflict","rollbackFailed","writeRolledBack","verifyFailed"].includes(value)) return copy.rbConfigError;
  if (["remoteUnsupported","dependencyMissing","cliUnsupported","customHome","rootForbidden"].includes(value)) return copy.rbDependencyError;
  if (["portInUse","invalidPort"].includes(value)) return copy.rbPortError;
  if (["proxyUnavailable","activeChanged"].includes(value)) return copy.rbActiveError;
  return copy.rbFailed;
}
